version: "3.9"

networks:
  jenkins-network:
    name: jenkins

volumes:
  data:
    name: jenkins-data
  certs:
    name: jenkins-docker-certs

services:
  master:
    image: jenkins/jenkins:2.375.2
    container_name: jenkins
    privileged: true
    networks:
      - jenkins-network
    user: root
    environment:
      - TZ=America/Toronto
    restart: always
    volumes:
      - data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:8080
      - 50000:50000
  agent:
    image: hachikoapp/jenkins-dind-slave:0.0.6
    privileged: true
    user: root
    container_name: agent
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC4bEp09GBDEmAVn3vbtmJCaTvM9jPyR6yEibni+Aw9PhToj8/n9sVAlfwR6uAANrXLxnFuJODzlaMwNKME3gYkJnRqyrkvSNDyK3okN1ibO2yqwc7nUFLwJLXlpyDnQZvEtlCXiZOHJcWgH0GaqKmuOsvRfcB6puzEtfZ1Gb4MklEzhlv/zRue7wqygsewrsQn9gl0c8udsSc5Rr1rSODAtr2tQhn1WaXqIT6L44MX9q8w/WbkdIkmFVuSGAHglivCjN2oqc4sHnjGd34Ht5qHr4Ga+wZZ1PQ+0j09PZ0zq8eBPpkBJycO6j5Fn7B8l1uB5hovnVKwFTiULwGchAVvdAYy9LXfR0RkW7oW1+4kGyJuP1lAXy1UTI9UwAgcajsOS3x6C+6ANxIv6g7R8eg0lMHobSkBDlsSlvc/kS2cao9yR794bKHHNwGPy0rNKRUZAXJaVTgW6RiLgAAFdZdA6nQnwXDXRmwgdtUfS5IxyMu9tU9Kp5RntvYhtv5nig4c6NdtsLqY7dea6cyNOrNjaILnDSm48OO9Bm5FGBin3BZ6b+D9Sm56fY0s7bFO6JD72ukI7FuOmDb2+uxGx96eWm9YgBufzSaPhReUdVq5qqkQCrP9+aom+nyO/zcwRwDhtv2JqkqbAMSQPza5d8VOIin1jXRsL+8Lz2aSOdsJ/Q== william@cloud-station
    networks:
      jenkins-network:
        aliases:
          - docker
    volumes:
      - data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - master

  # slave:
  #   image: 777777777777.dkr.ecr.us-west-2.amazonaws.com/jenkins-slave:latest
  #   container_name: slave
  #   user: jenkins
  #   environment:
  #     - TZ=America/Toronto
  #   restart: always
  #   environment:
  #     - SLAVE_NAME=us
  #     - SLAVE_SECRET=p77c7fea7b7f777c777df77777de77777a77b777777c77777777777b7777c777
  #   volumes:
  #     # - /slave1/workspace/:/workspace/
  #     - /data/:/data/
  #     # - $HOME/slave:/var/jenkins_home
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   depends_on:
  #     - master