version: "3.9"

networks:
  jenkins-network:
    name: jenkins

volumes:
  data:
    name: jenkins-data
  certs:
    name: jenkins-docker-certs

services:
  master:
    image: jenkins/jenkins:2.375.2
    container_name: jenkins
    networks:
      - jenkins-network
    user: root
    environment:
      - TZ=America/Toronto
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    restart: always
    volumes:
      - data:/var/jenkins_home
      - certs:/certs/client:ro
    ports:
      - 80:8080
      - 50000:50000

  dind:
    image: docker:dind
    container_name: jenkins-docker
    user: root
    privileged: true
    restart: unless-stopped
    networks:
      jenkins-network:
        aliases:
          - docker
    environment:
      - TZ=America/Toronto
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - data:/var/jenkins_home
      - certs:/certs/client
    depends_on:
      - master
  # slave:
  #   image: 777777777777.dkr.ecr.us-west-2.amazonaws.com/jenkins-slave:latest
  #   container_name: slave
  #   user: jenkins
  #   environment:
  #     - TZ=America/Toronto
  #   restart: always
  #   environment:
  #     - SLAVE_NAME=us
  #     - SLAVE_SECRET=p77c7fea7b7f777c777df77777de77777a77b777777c77777777777b7777c777
  #   volumes:
  #     # - /slave1/workspace/:/workspace/
  #     - /data/:/data/
  #     # - $HOME/slave:/var/jenkins_home
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   depends_on:
  #     - master